language: python
services:
  - docker
install:
  - make deps
script:
  - make test
script:
- make test
- make lint
- make docker_build
- make docker_push
deploy:
  provider: heroku
  app: guarded-island-29068
  api_key: ${HEROKU_API_KEY}
